// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"devops-console-backend/internal/dal/model"
)

func newAuthConfig(db *gorm.DB, opts ...gen.DOOption) authConfig {
	_authConfig := authConfig{}

	_authConfig.authConfigDo.UseDB(db, opts...)
	_authConfig.authConfigDo.UseModel(&model.AuthConfig{})

	tableName := _authConfig.authConfigDo.TableName()
	_authConfig.ALL = field.NewAsterisk(tableName)
	_authConfig.ID = field.NewUint32(tableName, "id")
	_authConfig.ResourceType = field.NewString(tableName, "resource_type")
	_authConfig.ResourceID = field.NewUint64(tableName, "resource_id")
	_authConfig.ResourceName = field.NewString(tableName, "resource_name")
	_authConfig.AuthType = field.NewString(tableName, "auth_type")
	_authConfig.ConfigKey = field.NewString(tableName, "config_key")
	_authConfig.ConfigValue = field.NewString(tableName, "config_value")
	_authConfig.IsEncrypted = field.NewBool(tableName, "is_encrypted")
	_authConfig.Status = field.NewString(tableName, "status")
	_authConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_authConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_authConfig.fillFieldMap()

	return _authConfig
}

type authConfig struct {
	authConfigDo

	ALL          field.Asterisk
	ID           field.Uint32
	ResourceType field.String
	ResourceID   field.Uint64
	ResourceName field.String
	AuthType     field.String
	ConfigKey    field.String
	ConfigValue  field.String
	IsEncrypted  field.Bool
	Status       field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (a authConfig) Table(newTableName string) *authConfig {
	a.authConfigDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a authConfig) As(alias string) *authConfig {
	a.authConfigDo.DO = *(a.authConfigDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *authConfig) updateTableName(table string) *authConfig {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint32(table, "id")
	a.ResourceType = field.NewString(table, "resource_type")
	a.ResourceID = field.NewUint64(table, "resource_id")
	a.ResourceName = field.NewString(table, "resource_name")
	a.AuthType = field.NewString(table, "auth_type")
	a.ConfigKey = field.NewString(table, "config_key")
	a.ConfigValue = field.NewString(table, "config_value")
	a.IsEncrypted = field.NewBool(table, "is_encrypted")
	a.Status = field.NewString(table, "status")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *authConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *authConfig) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 11)
	a.fieldMap["id"] = a.ID
	a.fieldMap["resource_type"] = a.ResourceType
	a.fieldMap["resource_id"] = a.ResourceID
	a.fieldMap["resource_name"] = a.ResourceName
	a.fieldMap["auth_type"] = a.AuthType
	a.fieldMap["config_key"] = a.ConfigKey
	a.fieldMap["config_value"] = a.ConfigValue
	a.fieldMap["is_encrypted"] = a.IsEncrypted
	a.fieldMap["status"] = a.Status
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a authConfig) clone(db *gorm.DB) authConfig {
	a.authConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a authConfig) replaceDB(db *gorm.DB) authConfig {
	a.authConfigDo.ReplaceDB(db)
	return a
}

type authConfigDo struct{ gen.DO }

type IAuthConfigDo interface {
	gen.SubQuery
	Debug() IAuthConfigDo
	WithContext(ctx context.Context) IAuthConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAuthConfigDo
	WriteDB() IAuthConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAuthConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAuthConfigDo
	Not(conds ...gen.Condition) IAuthConfigDo
	Or(conds ...gen.Condition) IAuthConfigDo
	Select(conds ...field.Expr) IAuthConfigDo
	Where(conds ...gen.Condition) IAuthConfigDo
	Order(conds ...field.Expr) IAuthConfigDo
	Distinct(cols ...field.Expr) IAuthConfigDo
	Omit(cols ...field.Expr) IAuthConfigDo
	Join(table schema.Tabler, on ...field.Expr) IAuthConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAuthConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAuthConfigDo
	Group(cols ...field.Expr) IAuthConfigDo
	Having(conds ...gen.Condition) IAuthConfigDo
	Limit(limit int) IAuthConfigDo
	Offset(offset int) IAuthConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthConfigDo
	Unscoped() IAuthConfigDo
	Create(values ...*model.AuthConfig) error
	CreateInBatches(values []*model.AuthConfig, batchSize int) error
	Save(values ...*model.AuthConfig) error
	First() (*model.AuthConfig, error)
	Take() (*model.AuthConfig, error)
	Last() (*model.AuthConfig, error)
	Find() ([]*model.AuthConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthConfig, err error)
	FindInBatches(result *[]*model.AuthConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AuthConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAuthConfigDo
	Assign(attrs ...field.AssignExpr) IAuthConfigDo
	Joins(fields ...field.RelationField) IAuthConfigDo
	Preload(fields ...field.RelationField) IAuthConfigDo
	FirstOrInit() (*model.AuthConfig, error)
	FirstOrCreate() (*model.AuthConfig, error)
	FindByPage(offset int, limit int) (result []*model.AuthConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAuthConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a authConfigDo) Debug() IAuthConfigDo {
	return a.withDO(a.DO.Debug())
}

func (a authConfigDo) WithContext(ctx context.Context) IAuthConfigDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a authConfigDo) ReadDB() IAuthConfigDo {
	return a.Clauses(dbresolver.Read)
}

func (a authConfigDo) WriteDB() IAuthConfigDo {
	return a.Clauses(dbresolver.Write)
}

func (a authConfigDo) Session(config *gorm.Session) IAuthConfigDo {
	return a.withDO(a.DO.Session(config))
}

func (a authConfigDo) Clauses(conds ...clause.Expression) IAuthConfigDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a authConfigDo) Returning(value interface{}, columns ...string) IAuthConfigDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a authConfigDo) Not(conds ...gen.Condition) IAuthConfigDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a authConfigDo) Or(conds ...gen.Condition) IAuthConfigDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a authConfigDo) Select(conds ...field.Expr) IAuthConfigDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a authConfigDo) Where(conds ...gen.Condition) IAuthConfigDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a authConfigDo) Order(conds ...field.Expr) IAuthConfigDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a authConfigDo) Distinct(cols ...field.Expr) IAuthConfigDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a authConfigDo) Omit(cols ...field.Expr) IAuthConfigDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a authConfigDo) Join(table schema.Tabler, on ...field.Expr) IAuthConfigDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a authConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAuthConfigDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a authConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IAuthConfigDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a authConfigDo) Group(cols ...field.Expr) IAuthConfigDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a authConfigDo) Having(conds ...gen.Condition) IAuthConfigDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a authConfigDo) Limit(limit int) IAuthConfigDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a authConfigDo) Offset(offset int) IAuthConfigDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a authConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthConfigDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a authConfigDo) Unscoped() IAuthConfigDo {
	return a.withDO(a.DO.Unscoped())
}

func (a authConfigDo) Create(values ...*model.AuthConfig) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a authConfigDo) CreateInBatches(values []*model.AuthConfig, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a authConfigDo) Save(values ...*model.AuthConfig) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a authConfigDo) First() (*model.AuthConfig, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthConfig), nil
	}
}

func (a authConfigDo) Take() (*model.AuthConfig, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthConfig), nil
	}
}

func (a authConfigDo) Last() (*model.AuthConfig, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthConfig), nil
	}
}

func (a authConfigDo) Find() ([]*model.AuthConfig, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuthConfig), err
}

func (a authConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthConfig, err error) {
	buf := make([]*model.AuthConfig, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a authConfigDo) FindInBatches(result *[]*model.AuthConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a authConfigDo) Attrs(attrs ...field.AssignExpr) IAuthConfigDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a authConfigDo) Assign(attrs ...field.AssignExpr) IAuthConfigDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a authConfigDo) Joins(fields ...field.RelationField) IAuthConfigDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a authConfigDo) Preload(fields ...field.RelationField) IAuthConfigDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a authConfigDo) FirstOrInit() (*model.AuthConfig, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthConfig), nil
	}
}

func (a authConfigDo) FirstOrCreate() (*model.AuthConfig, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthConfig), nil
	}
}

func (a authConfigDo) FindByPage(offset int, limit int) (result []*model.AuthConfig, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a authConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a authConfigDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a authConfigDo) Delete(models ...*model.AuthConfig) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *authConfigDo) withDO(do gen.Dao) *authConfigDo {
	a.DO = *do.(*gen.DO)
	return a
}
