// Status generated by gorm.io/gen. DO NOT EDIT.
// Status generated by gorm.io/gen. DO NOT EDIT.
// Status generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"devops-console-backend/internal/dal/model"
)

func newConnectionTest(db *gorm.DB, opts ...gen.DOOption) connectionTest {
	_connectionTest := connectionTest{}

	_connectionTest.connectionTestDo.UseDB(db, opts...)
	_connectionTest.connectionTestDo.UseModel(&model.ConnectionTest{})

	tableName := _connectionTest.connectionTestDo.TableName()
	_connectionTest.ALL = field.NewAsterisk(tableName)
	_connectionTest.ID = field.NewUint32(tableName, "id")
	_connectionTest.ResourceType = field.NewString(tableName, "resource_type")
	_connectionTest.ResourceID = field.NewUint64(tableName, "resource_id")
	_connectionTest.TestResult = field.NewString(tableName, "test_result")
	_connectionTest.ResponseTime = field.NewInt64(tableName, "response_time")
	_connectionTest.ErrorMessage = field.NewString(tableName, "error_message")
	_connectionTest.TestedAt = field.NewTime(tableName, "tested_at")

	_connectionTest.fillFieldMap()

	return _connectionTest
}

type connectionTest struct {
	connectionTestDo

	ALL          field.Asterisk
	ID           field.Uint32
	ResourceType field.String
	ResourceID   field.Uint64
	TestResult   field.String
	ResponseTime field.Int64
	ErrorMessage field.String
	TestedAt     field.Time

	fieldMap map[string]field.Expr
}

func (c connectionTest) Table(newTableName string) *connectionTest {
	c.connectionTestDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c connectionTest) As(alias string) *connectionTest {
	c.connectionTestDo.DO = *(c.connectionTestDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *connectionTest) updateTableName(table string) *connectionTest {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint32(table, "id")
	c.ResourceType = field.NewString(table, "resource_type")
	c.ResourceID = field.NewUint64(table, "resource_id")
	c.TestResult = field.NewString(table, "test_result")
	c.ResponseTime = field.NewInt64(table, "response_time")
	c.ErrorMessage = field.NewString(table, "error_message")
	c.TestedAt = field.NewTime(table, "tested_at")

	c.fillFieldMap()

	return c
}

func (c *connectionTest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *connectionTest) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.ID
	c.fieldMap["resource_type"] = c.ResourceType
	c.fieldMap["resource_id"] = c.ResourceID
	c.fieldMap["test_result"] = c.TestResult
	c.fieldMap["response_time"] = c.ResponseTime
	c.fieldMap["error_message"] = c.ErrorMessage
	c.fieldMap["tested_at"] = c.TestedAt
}

func (c connectionTest) clone(db *gorm.DB) connectionTest {
	c.connectionTestDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c connectionTest) replaceDB(db *gorm.DB) connectionTest {
	c.connectionTestDo.ReplaceDB(db)
	return c
}

type connectionTestDo struct{ gen.DO }

type IConnectionTestDo interface {
	gen.SubQuery
	Debug() IConnectionTestDo
	WithContext(ctx context.Context) IConnectionTestDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConnectionTestDo
	WriteDB() IConnectionTestDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConnectionTestDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConnectionTestDo
	Not(conds ...gen.Condition) IConnectionTestDo
	Or(conds ...gen.Condition) IConnectionTestDo
	Select(conds ...field.Expr) IConnectionTestDo
	Where(conds ...gen.Condition) IConnectionTestDo
	Order(conds ...field.Expr) IConnectionTestDo
	Distinct(cols ...field.Expr) IConnectionTestDo
	Omit(cols ...field.Expr) IConnectionTestDo
	Join(table schema.Tabler, on ...field.Expr) IConnectionTestDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConnectionTestDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConnectionTestDo
	Group(cols ...field.Expr) IConnectionTestDo
	Having(conds ...gen.Condition) IConnectionTestDo
	Limit(limit int) IConnectionTestDo
	Offset(offset int) IConnectionTestDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConnectionTestDo
	Unscoped() IConnectionTestDo
	Create(values ...*model.ConnectionTest) error
	CreateInBatches(values []*model.ConnectionTest, batchSize int) error
	Save(values ...*model.ConnectionTest) error
	First() (*model.ConnectionTest, error)
	Take() (*model.ConnectionTest, error)
	Last() (*model.ConnectionTest, error)
	Find() ([]*model.ConnectionTest, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConnectionTest, err error)
	FindInBatches(result *[]*model.ConnectionTest, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ConnectionTest) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConnectionTestDo
	Assign(attrs ...field.AssignExpr) IConnectionTestDo
	Joins(fields ...field.RelationField) IConnectionTestDo
	Preload(fields ...field.RelationField) IConnectionTestDo
	FirstOrInit() (*model.ConnectionTest, error)
	FirstOrCreate() (*model.ConnectionTest, error)
	FindByPage(offset int, limit int) (result []*model.ConnectionTest, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConnectionTestDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c connectionTestDo) Debug() IConnectionTestDo {
	return c.withDO(c.DO.Debug())
}

func (c connectionTestDo) WithContext(ctx context.Context) IConnectionTestDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c connectionTestDo) ReadDB() IConnectionTestDo {
	return c.Clauses(dbresolver.Read)
}

func (c connectionTestDo) WriteDB() IConnectionTestDo {
	return c.Clauses(dbresolver.Write)
}

func (c connectionTestDo) Session(config *gorm.Session) IConnectionTestDo {
	return c.withDO(c.DO.Session(config))
}

func (c connectionTestDo) Clauses(conds ...clause.Expression) IConnectionTestDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c connectionTestDo) Returning(value interface{}, columns ...string) IConnectionTestDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c connectionTestDo) Not(conds ...gen.Condition) IConnectionTestDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c connectionTestDo) Or(conds ...gen.Condition) IConnectionTestDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c connectionTestDo) Select(conds ...field.Expr) IConnectionTestDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c connectionTestDo) Where(conds ...gen.Condition) IConnectionTestDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c connectionTestDo) Order(conds ...field.Expr) IConnectionTestDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c connectionTestDo) Distinct(cols ...field.Expr) IConnectionTestDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c connectionTestDo) Omit(cols ...field.Expr) IConnectionTestDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c connectionTestDo) Join(table schema.Tabler, on ...field.Expr) IConnectionTestDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c connectionTestDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConnectionTestDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c connectionTestDo) RightJoin(table schema.Tabler, on ...field.Expr) IConnectionTestDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c connectionTestDo) Group(cols ...field.Expr) IConnectionTestDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c connectionTestDo) Having(conds ...gen.Condition) IConnectionTestDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c connectionTestDo) Limit(limit int) IConnectionTestDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c connectionTestDo) Offset(offset int) IConnectionTestDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c connectionTestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConnectionTestDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c connectionTestDo) Unscoped() IConnectionTestDo {
	return c.withDO(c.DO.Unscoped())
}

func (c connectionTestDo) Create(values ...*model.ConnectionTest) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c connectionTestDo) CreateInBatches(values []*model.ConnectionTest, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c connectionTestDo) Save(values ...*model.ConnectionTest) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c connectionTestDo) First() (*model.ConnectionTest, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConnectionTest), nil
	}
}

func (c connectionTestDo) Take() (*model.ConnectionTest, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConnectionTest), nil
	}
}

func (c connectionTestDo) Last() (*model.ConnectionTest, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConnectionTest), nil
	}
}

func (c connectionTestDo) Find() ([]*model.ConnectionTest, error) {
	result, err := c.DO.Find()
	return result.([]*model.ConnectionTest), err
}

func (c connectionTestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConnectionTest, err error) {
	buf := make([]*model.ConnectionTest, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c connectionTestDo) FindInBatches(result *[]*model.ConnectionTest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c connectionTestDo) Attrs(attrs ...field.AssignExpr) IConnectionTestDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c connectionTestDo) Assign(attrs ...field.AssignExpr) IConnectionTestDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c connectionTestDo) Joins(fields ...field.RelationField) IConnectionTestDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c connectionTestDo) Preload(fields ...field.RelationField) IConnectionTestDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c connectionTestDo) FirstOrInit() (*model.ConnectionTest, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConnectionTest), nil
	}
}

func (c connectionTestDo) FirstOrCreate() (*model.ConnectionTest, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConnectionTest), nil
	}
}

func (c connectionTestDo) FindByPage(offset int, limit int) (result []*model.ConnectionTest, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c connectionTestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c connectionTestDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c connectionTestDo) Delete(models ...*model.ConnectionTest) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *connectionTestDo) withDO(do gen.Dao) *connectionTestDo {
	c.DO = *do.(*gen.DO)
	return c
}
