// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	AuthConfig      *authConfig
	ConnectionTest  *connectionTest
	Instance        *instance
	InstanceType    *instanceType
	Pipeline        *pipeline
	PipelineRun     *pipelineRun
	PipelineStep    *pipelineStep
	Project         *project
	ResourceDetail  *resourceDetail
	SystemUser      *systemUser
	SystemUserToken *systemUserToken
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AuthConfig = &Q.AuthConfig
	ConnectionTest = &Q.ConnectionTest
	Instance = &Q.Instance
	InstanceType = &Q.InstanceType
	Pipeline = &Q.Pipeline
	PipelineRun = &Q.PipelineRun
	PipelineStep = &Q.PipelineStep
	Project = &Q.Project
	ResourceDetail = &Q.ResourceDetail
	SystemUser = &Q.SystemUser
	SystemUserToken = &Q.SystemUserToken
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		AuthConfig:      newAuthConfig(db, opts...),
		ConnectionTest:  newConnectionTest(db, opts...),
		Instance:        newInstance(db, opts...),
		InstanceType:    newInstanceType(db, opts...),
		Pipeline:        newPipeline(db, opts...),
		PipelineRun:     newPipelineRun(db, opts...),
		PipelineStep:    newPipelineStep(db, opts...),
		Project:         newProject(db, opts...),
		ResourceDetail:  newResourceDetail(db, opts...),
		SystemUser:      newSystemUser(db, opts...),
		SystemUserToken: newSystemUserToken(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AuthConfig      authConfig
	ConnectionTest  connectionTest
	Instance        instance
	InstanceType    instanceType
	Pipeline        pipeline
	PipelineRun     pipelineRun
	PipelineStep    pipelineStep
	Project         project
	ResourceDetail  resourceDetail
	SystemUser      systemUser
	SystemUserToken systemUserToken
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		AuthConfig:      q.AuthConfig.clone(db),
		ConnectionTest:  q.ConnectionTest.clone(db),
		Instance:        q.Instance.clone(db),
		InstanceType:    q.InstanceType.clone(db),
		Pipeline:        q.Pipeline.clone(db),
		PipelineRun:     q.PipelineRun.clone(db),
		PipelineStep:    q.PipelineStep.clone(db),
		Project:         q.Project.clone(db),
		ResourceDetail:  q.ResourceDetail.clone(db),
		SystemUser:      q.SystemUser.clone(db),
		SystemUserToken: q.SystemUserToken.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		AuthConfig:      q.AuthConfig.replaceDB(db),
		ConnectionTest:  q.ConnectionTest.replaceDB(db),
		Instance:        q.Instance.replaceDB(db),
		InstanceType:    q.InstanceType.replaceDB(db),
		Pipeline:        q.Pipeline.replaceDB(db),
		PipelineRun:     q.PipelineRun.replaceDB(db),
		PipelineStep:    q.PipelineStep.replaceDB(db),
		Project:         q.Project.replaceDB(db),
		ResourceDetail:  q.ResourceDetail.replaceDB(db),
		SystemUser:      q.SystemUser.replaceDB(db),
		SystemUserToken: q.SystemUserToken.replaceDB(db),
	}
}

type queryCtx struct {
	AuthConfig      IAuthConfigDo
	ConnectionTest  IConnectionTestDo
	Instance        IInstanceDo
	InstanceType    IInstanceTypeDo
	Pipeline        IPipelineDo
	PipelineRun     IPipelineRunDo
	PipelineStep    IPipelineStepDo
	Project         IProjectDo
	ResourceDetail  IResourceDetailDo
	SystemUser      ISystemUserDo
	SystemUserToken ISystemUserTokenDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AuthConfig:      q.AuthConfig.WithContext(ctx),
		ConnectionTest:  q.ConnectionTest.WithContext(ctx),
		Instance:        q.Instance.WithContext(ctx),
		InstanceType:    q.InstanceType.WithContext(ctx),
		Pipeline:        q.Pipeline.WithContext(ctx),
		PipelineRun:     q.PipelineRun.WithContext(ctx),
		PipelineStep:    q.PipelineStep.WithContext(ctx),
		Project:         q.Project.WithContext(ctx),
		ResourceDetail:  q.ResourceDetail.WithContext(ctx),
		SystemUser:      q.SystemUser.WithContext(ctx),
		SystemUserToken: q.SystemUserToken.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
