// Status generated by gorm.io/gen. DO NOT EDIT.
// Status generated by gorm.io/gen. DO NOT EDIT.
// Status generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"devops-console-backend/internal/dal/model"
)

func newInstanceType(db *gorm.DB, opts ...gen.DOOption) instanceType {
	_instanceType := instanceType{}

	_instanceType.instanceTypeDo.UseDB(db, opts...)
	_instanceType.instanceTypeDo.UseModel(&model.InstanceType{})

	tableName := _instanceType.instanceTypeDo.TableName()
	_instanceType.ALL = field.NewAsterisk(tableName)
	_instanceType.ID = field.NewUint32(tableName, "id")
	_instanceType.TypeName = field.NewString(tableName, "type_name")
	_instanceType.Description = field.NewString(tableName, "description")
	_instanceType.CreatedAt = field.NewTime(tableName, "created_at")
	_instanceType.UpdatedAt = field.NewTime(tableName, "updated_at")

	_instanceType.fillFieldMap()

	return _instanceType
}

type instanceType struct {
	instanceTypeDo

	ALL         field.Asterisk
	ID          field.Uint32
	TypeName    field.String
	Description field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (i instanceType) Table(newTableName string) *instanceType {
	i.instanceTypeDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i instanceType) As(alias string) *instanceType {
	i.instanceTypeDo.DO = *(i.instanceTypeDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *instanceType) updateTableName(table string) *instanceType {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewUint32(table, "id")
	i.TypeName = field.NewString(table, "type_name")
	i.Description = field.NewString(table, "description")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *instanceType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *instanceType) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 5)
	i.fieldMap["id"] = i.ID
	i.fieldMap["type_name"] = i.TypeName
	i.fieldMap["description"] = i.Description
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i instanceType) clone(db *gorm.DB) instanceType {
	i.instanceTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i instanceType) replaceDB(db *gorm.DB) instanceType {
	i.instanceTypeDo.ReplaceDB(db)
	return i
}

type instanceTypeDo struct{ gen.DO }

type IInstanceTypeDo interface {
	gen.SubQuery
	Debug() IInstanceTypeDo
	WithContext(ctx context.Context) IInstanceTypeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInstanceTypeDo
	WriteDB() IInstanceTypeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInstanceTypeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInstanceTypeDo
	Not(conds ...gen.Condition) IInstanceTypeDo
	Or(conds ...gen.Condition) IInstanceTypeDo
	Select(conds ...field.Expr) IInstanceTypeDo
	Where(conds ...gen.Condition) IInstanceTypeDo
	Order(conds ...field.Expr) IInstanceTypeDo
	Distinct(cols ...field.Expr) IInstanceTypeDo
	Omit(cols ...field.Expr) IInstanceTypeDo
	Join(table schema.Tabler, on ...field.Expr) IInstanceTypeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInstanceTypeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInstanceTypeDo
	Group(cols ...field.Expr) IInstanceTypeDo
	Having(conds ...gen.Condition) IInstanceTypeDo
	Limit(limit int) IInstanceTypeDo
	Offset(offset int) IInstanceTypeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInstanceTypeDo
	Unscoped() IInstanceTypeDo
	Create(values ...*model.InstanceType) error
	CreateInBatches(values []*model.InstanceType, batchSize int) error
	Save(values ...*model.InstanceType) error
	First() (*model.InstanceType, error)
	Take() (*model.InstanceType, error)
	Last() (*model.InstanceType, error)
	Find() ([]*model.InstanceType, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InstanceType, err error)
	FindInBatches(result *[]*model.InstanceType, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.InstanceType) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInstanceTypeDo
	Assign(attrs ...field.AssignExpr) IInstanceTypeDo
	Joins(fields ...field.RelationField) IInstanceTypeDo
	Preload(fields ...field.RelationField) IInstanceTypeDo
	FirstOrInit() (*model.InstanceType, error)
	FirstOrCreate() (*model.InstanceType, error)
	FindByPage(offset int, limit int) (result []*model.InstanceType, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInstanceTypeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i instanceTypeDo) Debug() IInstanceTypeDo {
	return i.withDO(i.DO.Debug())
}

func (i instanceTypeDo) WithContext(ctx context.Context) IInstanceTypeDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i instanceTypeDo) ReadDB() IInstanceTypeDo {
	return i.Clauses(dbresolver.Read)
}

func (i instanceTypeDo) WriteDB() IInstanceTypeDo {
	return i.Clauses(dbresolver.Write)
}

func (i instanceTypeDo) Session(config *gorm.Session) IInstanceTypeDo {
	return i.withDO(i.DO.Session(config))
}

func (i instanceTypeDo) Clauses(conds ...clause.Expression) IInstanceTypeDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i instanceTypeDo) Returning(value interface{}, columns ...string) IInstanceTypeDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i instanceTypeDo) Not(conds ...gen.Condition) IInstanceTypeDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i instanceTypeDo) Or(conds ...gen.Condition) IInstanceTypeDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i instanceTypeDo) Select(conds ...field.Expr) IInstanceTypeDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i instanceTypeDo) Where(conds ...gen.Condition) IInstanceTypeDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i instanceTypeDo) Order(conds ...field.Expr) IInstanceTypeDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i instanceTypeDo) Distinct(cols ...field.Expr) IInstanceTypeDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i instanceTypeDo) Omit(cols ...field.Expr) IInstanceTypeDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i instanceTypeDo) Join(table schema.Tabler, on ...field.Expr) IInstanceTypeDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i instanceTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInstanceTypeDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i instanceTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) IInstanceTypeDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i instanceTypeDo) Group(cols ...field.Expr) IInstanceTypeDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i instanceTypeDo) Having(conds ...gen.Condition) IInstanceTypeDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i instanceTypeDo) Limit(limit int) IInstanceTypeDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i instanceTypeDo) Offset(offset int) IInstanceTypeDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i instanceTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInstanceTypeDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i instanceTypeDo) Unscoped() IInstanceTypeDo {
	return i.withDO(i.DO.Unscoped())
}

func (i instanceTypeDo) Create(values ...*model.InstanceType) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i instanceTypeDo) CreateInBatches(values []*model.InstanceType, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i instanceTypeDo) Save(values ...*model.InstanceType) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i instanceTypeDo) First() (*model.InstanceType, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceType), nil
	}
}

func (i instanceTypeDo) Take() (*model.InstanceType, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceType), nil
	}
}

func (i instanceTypeDo) Last() (*model.InstanceType, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceType), nil
	}
}

func (i instanceTypeDo) Find() ([]*model.InstanceType, error) {
	result, err := i.DO.Find()
	return result.([]*model.InstanceType), err
}

func (i instanceTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InstanceType, err error) {
	buf := make([]*model.InstanceType, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i instanceTypeDo) FindInBatches(result *[]*model.InstanceType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i instanceTypeDo) Attrs(attrs ...field.AssignExpr) IInstanceTypeDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i instanceTypeDo) Assign(attrs ...field.AssignExpr) IInstanceTypeDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i instanceTypeDo) Joins(fields ...field.RelationField) IInstanceTypeDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i instanceTypeDo) Preload(fields ...field.RelationField) IInstanceTypeDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i instanceTypeDo) FirstOrInit() (*model.InstanceType, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceType), nil
	}
}

func (i instanceTypeDo) FirstOrCreate() (*model.InstanceType, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InstanceType), nil
	}
}

func (i instanceTypeDo) FindByPage(offset int, limit int) (result []*model.InstanceType, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i instanceTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i instanceTypeDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i instanceTypeDo) Delete(models ...*model.InstanceType) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *instanceTypeDo) withDO(do gen.Dao) *instanceTypeDo {
	i.DO = *do.(*gen.DO)
	return i
}
