// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"devops-console-backend/internal/dal/model"
)

func newInstance(db *gorm.DB, opts ...gen.DOOption) instance {
	_instance := instance{}

	_instance.instanceDo.UseDB(db, opts...)
	_instance.instanceDo.UseModel(&model.Instance{})

	tableName := _instance.instanceDo.TableName()
	_instance.ALL = field.NewAsterisk(tableName)
	_instance.ID = field.NewUint32(tableName, "id")
	_instance.InstanceTypeID = field.NewUint32(tableName, "instance_type_id")
	_instance.Name = field.NewString(tableName, "name")
	_instance.Address = field.NewString(tableName, "address")
	_instance.HTTPSEnabled = field.NewBool(tableName, "https_enabled")
	_instance.SkipSslVerify = field.NewBool(tableName, "skip_ssl_verify")
	_instance.Status = field.NewString(tableName, "status")
	_instance.CreatedAt = field.NewTime(tableName, "created_at")
	_instance.UpdatedAt = field.NewTime(tableName, "updated_at")

	_instance.fillFieldMap()

	return _instance
}

type instance struct {
	instanceDo

	ALL            field.Asterisk
	ID             field.Uint32
	InstanceTypeID field.Uint32
	Name           field.String
	Address        field.String
	HTTPSEnabled   field.Bool
	SkipSslVerify  field.Bool
	Status         field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (i instance) Table(newTableName string) *instance {
	i.instanceDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i instance) As(alias string) *instance {
	i.instanceDo.DO = *(i.instanceDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *instance) updateTableName(table string) *instance {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewUint32(table, "id")
	i.InstanceTypeID = field.NewUint32(table, "instance_type_id")
	i.Name = field.NewString(table, "name")
	i.Address = field.NewString(table, "address")
	i.HTTPSEnabled = field.NewBool(table, "https_enabled")
	i.SkipSslVerify = field.NewBool(table, "skip_ssl_verify")
	i.Status = field.NewString(table, "status")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *instance) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *instance) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 9)
	i.fieldMap["id"] = i.ID
	i.fieldMap["instance_type_id"] = i.InstanceTypeID
	i.fieldMap["name"] = i.Name
	i.fieldMap["address"] = i.Address
	i.fieldMap["https_enabled"] = i.HTTPSEnabled
	i.fieldMap["skip_ssl_verify"] = i.SkipSslVerify
	i.fieldMap["status"] = i.Status
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i instance) clone(db *gorm.DB) instance {
	i.instanceDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i instance) replaceDB(db *gorm.DB) instance {
	i.instanceDo.ReplaceDB(db)
	return i
}

type instanceDo struct{ gen.DO }

type IInstanceDo interface {
	gen.SubQuery
	Debug() IInstanceDo
	WithContext(ctx context.Context) IInstanceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInstanceDo
	WriteDB() IInstanceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInstanceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInstanceDo
	Not(conds ...gen.Condition) IInstanceDo
	Or(conds ...gen.Condition) IInstanceDo
	Select(conds ...field.Expr) IInstanceDo
	Where(conds ...gen.Condition) IInstanceDo
	Order(conds ...field.Expr) IInstanceDo
	Distinct(cols ...field.Expr) IInstanceDo
	Omit(cols ...field.Expr) IInstanceDo
	Join(table schema.Tabler, on ...field.Expr) IInstanceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInstanceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInstanceDo
	Group(cols ...field.Expr) IInstanceDo
	Having(conds ...gen.Condition) IInstanceDo
	Limit(limit int) IInstanceDo
	Offset(offset int) IInstanceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInstanceDo
	Unscoped() IInstanceDo
	Create(values ...*model.Instance) error
	CreateInBatches(values []*model.Instance, batchSize int) error
	Save(values ...*model.Instance) error
	First() (*model.Instance, error)
	Take() (*model.Instance, error)
	Last() (*model.Instance, error)
	Find() ([]*model.Instance, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Instance, err error)
	FindInBatches(result *[]*model.Instance, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Instance) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInstanceDo
	Assign(attrs ...field.AssignExpr) IInstanceDo
	Joins(fields ...field.RelationField) IInstanceDo
	Preload(fields ...field.RelationField) IInstanceDo
	FirstOrInit() (*model.Instance, error)
	FirstOrCreate() (*model.Instance, error)
	FindByPage(offset int, limit int) (result []*model.Instance, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInstanceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i instanceDo) Debug() IInstanceDo {
	return i.withDO(i.DO.Debug())
}

func (i instanceDo) WithContext(ctx context.Context) IInstanceDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i instanceDo) ReadDB() IInstanceDo {
	return i.Clauses(dbresolver.Read)
}

func (i instanceDo) WriteDB() IInstanceDo {
	return i.Clauses(dbresolver.Write)
}

func (i instanceDo) Session(config *gorm.Session) IInstanceDo {
	return i.withDO(i.DO.Session(config))
}

func (i instanceDo) Clauses(conds ...clause.Expression) IInstanceDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i instanceDo) Returning(value interface{}, columns ...string) IInstanceDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i instanceDo) Not(conds ...gen.Condition) IInstanceDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i instanceDo) Or(conds ...gen.Condition) IInstanceDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i instanceDo) Select(conds ...field.Expr) IInstanceDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i instanceDo) Where(conds ...gen.Condition) IInstanceDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i instanceDo) Order(conds ...field.Expr) IInstanceDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i instanceDo) Distinct(cols ...field.Expr) IInstanceDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i instanceDo) Omit(cols ...field.Expr) IInstanceDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i instanceDo) Join(table schema.Tabler, on ...field.Expr) IInstanceDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i instanceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInstanceDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i instanceDo) RightJoin(table schema.Tabler, on ...field.Expr) IInstanceDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i instanceDo) Group(cols ...field.Expr) IInstanceDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i instanceDo) Having(conds ...gen.Condition) IInstanceDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i instanceDo) Limit(limit int) IInstanceDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i instanceDo) Offset(offset int) IInstanceDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i instanceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInstanceDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i instanceDo) Unscoped() IInstanceDo {
	return i.withDO(i.DO.Unscoped())
}

func (i instanceDo) Create(values ...*model.Instance) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i instanceDo) CreateInBatches(values []*model.Instance, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i instanceDo) Save(values ...*model.Instance) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i instanceDo) First() (*model.Instance, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Instance), nil
	}
}

func (i instanceDo) Take() (*model.Instance, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Instance), nil
	}
}

func (i instanceDo) Last() (*model.Instance, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Instance), nil
	}
}

func (i instanceDo) Find() ([]*model.Instance, error) {
	result, err := i.DO.Find()
	return result.([]*model.Instance), err
}

func (i instanceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Instance, err error) {
	buf := make([]*model.Instance, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i instanceDo) FindInBatches(result *[]*model.Instance, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i instanceDo) Attrs(attrs ...field.AssignExpr) IInstanceDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i instanceDo) Assign(attrs ...field.AssignExpr) IInstanceDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i instanceDo) Joins(fields ...field.RelationField) IInstanceDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i instanceDo) Preload(fields ...field.RelationField) IInstanceDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i instanceDo) FirstOrInit() (*model.Instance, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Instance), nil
	}
}

func (i instanceDo) FirstOrCreate() (*model.Instance, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Instance), nil
	}
}

func (i instanceDo) FindByPage(offset int, limit int) (result []*model.Instance, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i instanceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i instanceDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i instanceDo) Delete(models ...*model.Instance) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *instanceDo) withDO(do gen.Dao) *instanceDo {
	i.DO = *do.(*gen.DO)
	return i
}
