// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"devops-console-backend/internal/dal/model"
)

func newPipelineStep(db *gorm.DB, opts ...gen.DOOption) pipelineStep {
	_pipelineStep := pipelineStep{}

	_pipelineStep.pipelineStepDo.UseDB(db, opts...)
	_pipelineStep.pipelineStepDo.UseModel(&model.PipelineStep{})

	tableName := _pipelineStep.pipelineStepDo.TableName()
	_pipelineStep.ALL = field.NewAsterisk(tableName)
	_pipelineStep.ID = field.NewUint32(tableName, "id")
	_pipelineStep.PipelineID = field.NewUint32(tableName, "pipeline_id")
	_pipelineStep.Name = field.NewString(tableName, "name")
	_pipelineStep.Image = field.NewString(tableName, "image")
	_pipelineStep.Commands = field.NewString(tableName, "commands")
	_pipelineStep.DependsOn = field.NewString(tableName, "depends_on")
	_pipelineStep.Sort = field.NewInt32(tableName, "sort")
	_pipelineStep.CreatedAt = field.NewTime(tableName, "created_at")
	_pipelineStep.DeletedAt = field.NewField(tableName, "deleted_at")

	_pipelineStep.fillFieldMap()

	return _pipelineStep
}

// pipelineStep 流水线步骤详情表
type pipelineStep struct {
	pipelineStepDo

	ALL        field.Asterisk
	ID         field.Uint32
	PipelineID field.Uint32 // 所属流水线ID
	Name       field.String // 步骤名称
	Image      field.String // 使用的镜像
	Commands   field.String // 运行命令
	DependsOn  field.String // 依赖的步骤名称
	Sort       field.Int32  // 排序
	CreatedAt  field.Time
	DeletedAt  field.Field // 删除时间

	fieldMap map[string]field.Expr
}

func (p pipelineStep) Table(newTableName string) *pipelineStep {
	p.pipelineStepDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pipelineStep) As(alias string) *pipelineStep {
	p.pipelineStepDo.DO = *(p.pipelineStepDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pipelineStep) updateTableName(table string) *pipelineStep {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint32(table, "id")
	p.PipelineID = field.NewUint32(table, "pipeline_id")
	p.Name = field.NewString(table, "name")
	p.Image = field.NewString(table, "image")
	p.Commands = field.NewString(table, "commands")
	p.DependsOn = field.NewString(table, "depends_on")
	p.Sort = field.NewInt32(table, "sort")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.DeletedAt = field.NewField(table, "deleted_at")

	p.fillFieldMap()

	return p
}

func (p *pipelineStep) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pipelineStep) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["pipeline_id"] = p.PipelineID
	p.fieldMap["name"] = p.Name
	p.fieldMap["image"] = p.Image
	p.fieldMap["commands"] = p.Commands
	p.fieldMap["depends_on"] = p.DependsOn
	p.fieldMap["sort"] = p.Sort
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
}

func (p pipelineStep) clone(db *gorm.DB) pipelineStep {
	p.pipelineStepDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pipelineStep) replaceDB(db *gorm.DB) pipelineStep {
	p.pipelineStepDo.ReplaceDB(db)
	return p
}

type pipelineStepDo struct{ gen.DO }

type IPipelineStepDo interface {
	gen.SubQuery
	Debug() IPipelineStepDo
	WithContext(ctx context.Context) IPipelineStepDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPipelineStepDo
	WriteDB() IPipelineStepDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPipelineStepDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPipelineStepDo
	Not(conds ...gen.Condition) IPipelineStepDo
	Or(conds ...gen.Condition) IPipelineStepDo
	Select(conds ...field.Expr) IPipelineStepDo
	Where(conds ...gen.Condition) IPipelineStepDo
	Order(conds ...field.Expr) IPipelineStepDo
	Distinct(cols ...field.Expr) IPipelineStepDo
	Omit(cols ...field.Expr) IPipelineStepDo
	Join(table schema.Tabler, on ...field.Expr) IPipelineStepDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPipelineStepDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPipelineStepDo
	Group(cols ...field.Expr) IPipelineStepDo
	Having(conds ...gen.Condition) IPipelineStepDo
	Limit(limit int) IPipelineStepDo
	Offset(offset int) IPipelineStepDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPipelineStepDo
	Unscoped() IPipelineStepDo
	Create(values ...*model.PipelineStep) error
	CreateInBatches(values []*model.PipelineStep, batchSize int) error
	Save(values ...*model.PipelineStep) error
	First() (*model.PipelineStep, error)
	Take() (*model.PipelineStep, error)
	Last() (*model.PipelineStep, error)
	Find() ([]*model.PipelineStep, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PipelineStep, err error)
	FindInBatches(result *[]*model.PipelineStep, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PipelineStep) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPipelineStepDo
	Assign(attrs ...field.AssignExpr) IPipelineStepDo
	Joins(fields ...field.RelationField) IPipelineStepDo
	Preload(fields ...field.RelationField) IPipelineStepDo
	FirstOrInit() (*model.PipelineStep, error)
	FirstOrCreate() (*model.PipelineStep, error)
	FindByPage(offset int, limit int) (result []*model.PipelineStep, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPipelineStepDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p pipelineStepDo) Debug() IPipelineStepDo {
	return p.withDO(p.DO.Debug())
}

func (p pipelineStepDo) WithContext(ctx context.Context) IPipelineStepDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pipelineStepDo) ReadDB() IPipelineStepDo {
	return p.Clauses(dbresolver.Read)
}

func (p pipelineStepDo) WriteDB() IPipelineStepDo {
	return p.Clauses(dbresolver.Write)
}

func (p pipelineStepDo) Session(config *gorm.Session) IPipelineStepDo {
	return p.withDO(p.DO.Session(config))
}

func (p pipelineStepDo) Clauses(conds ...clause.Expression) IPipelineStepDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pipelineStepDo) Returning(value interface{}, columns ...string) IPipelineStepDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pipelineStepDo) Not(conds ...gen.Condition) IPipelineStepDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pipelineStepDo) Or(conds ...gen.Condition) IPipelineStepDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pipelineStepDo) Select(conds ...field.Expr) IPipelineStepDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pipelineStepDo) Where(conds ...gen.Condition) IPipelineStepDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pipelineStepDo) Order(conds ...field.Expr) IPipelineStepDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pipelineStepDo) Distinct(cols ...field.Expr) IPipelineStepDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pipelineStepDo) Omit(cols ...field.Expr) IPipelineStepDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pipelineStepDo) Join(table schema.Tabler, on ...field.Expr) IPipelineStepDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pipelineStepDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPipelineStepDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pipelineStepDo) RightJoin(table schema.Tabler, on ...field.Expr) IPipelineStepDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pipelineStepDo) Group(cols ...field.Expr) IPipelineStepDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pipelineStepDo) Having(conds ...gen.Condition) IPipelineStepDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pipelineStepDo) Limit(limit int) IPipelineStepDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pipelineStepDo) Offset(offset int) IPipelineStepDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pipelineStepDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPipelineStepDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pipelineStepDo) Unscoped() IPipelineStepDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pipelineStepDo) Create(values ...*model.PipelineStep) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pipelineStepDo) CreateInBatches(values []*model.PipelineStep, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pipelineStepDo) Save(values ...*model.PipelineStep) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pipelineStepDo) First() (*model.PipelineStep, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PipelineStep), nil
	}
}

func (p pipelineStepDo) Take() (*model.PipelineStep, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PipelineStep), nil
	}
}

func (p pipelineStepDo) Last() (*model.PipelineStep, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PipelineStep), nil
	}
}

func (p pipelineStepDo) Find() ([]*model.PipelineStep, error) {
	result, err := p.DO.Find()
	return result.([]*model.PipelineStep), err
}

func (p pipelineStepDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PipelineStep, err error) {
	buf := make([]*model.PipelineStep, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pipelineStepDo) FindInBatches(result *[]*model.PipelineStep, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pipelineStepDo) Attrs(attrs ...field.AssignExpr) IPipelineStepDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pipelineStepDo) Assign(attrs ...field.AssignExpr) IPipelineStepDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pipelineStepDo) Joins(fields ...field.RelationField) IPipelineStepDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pipelineStepDo) Preload(fields ...field.RelationField) IPipelineStepDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pipelineStepDo) FirstOrInit() (*model.PipelineStep, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PipelineStep), nil
	}
}

func (p pipelineStepDo) FirstOrCreate() (*model.PipelineStep, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PipelineStep), nil
	}
}

func (p pipelineStepDo) FindByPage(offset int, limit int) (result []*model.PipelineStep, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pipelineStepDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pipelineStepDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pipelineStepDo) Delete(models ...*model.PipelineStep) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pipelineStepDo) withDO(do gen.Dao) *pipelineStepDo {
	p.DO = *do.(*gen.DO)
	return p
}
