// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"devops-console-backend/internal/dal/model"
)

func newPipelineRun(db *gorm.DB, opts ...gen.DOOption) pipelineRun {
	_pipelineRun := pipelineRun{}

	_pipelineRun.pipelineRunDo.UseDB(db, opts...)
	_pipelineRun.pipelineRunDo.UseModel(&model.PipelineRun{})

	tableName := _pipelineRun.pipelineRunDo.TableName()
	_pipelineRun.ALL = field.NewAsterisk(tableName)
	_pipelineRun.ID = field.NewUint64(tableName, "id")
	_pipelineRun.PipelineID = field.NewUint32(tableName, "pipeline_id")
	_pipelineRun.WorkflowName = field.NewString(tableName, "workflow_name")
	_pipelineRun.Status = field.NewString(tableName, "status")
	_pipelineRun.Operator = field.NewString(tableName, "operator")
	_pipelineRun.Branch = field.NewString(tableName, "branch")
	_pipelineRun.CommitID = field.NewString(tableName, "commit_id")
	_pipelineRun.StartTime = field.NewTime(tableName, "start_time")
	_pipelineRun.EndTime = field.NewTime(tableName, "end_time")
	_pipelineRun.Duration = field.NewUint32(tableName, "duration")
	_pipelineRun.CreatedAt = field.NewTime(tableName, "created_at")
	_pipelineRun.UpdatedAt = field.NewTime(tableName, "updated_at")
	_pipelineRun.DeletedAt = field.NewField(tableName, "deleted_at")

	_pipelineRun.fillFieldMap()

	return _pipelineRun
}

// pipelineRun 流水线执行记录表
type pipelineRun struct {
	pipelineRunDo

	ALL          field.Asterisk
	ID           field.Uint64
	PipelineID   field.Uint32 // 关联流水线ID
	WorkflowName field.String // K8s中生成的Workflow名称
	Status       field.String // 运行状态
	Operator     field.String // 执行人
	Branch       field.String // 本次构建实际使用的分支
	CommitID     field.String // 代码CommitID
	StartTime    field.Time   // 开始时间
	EndTime      field.Time   // 结束时间
	Duration     field.Uint32 // 执行耗时，单位秒
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field

	fieldMap map[string]field.Expr
}

func (p pipelineRun) Table(newTableName string) *pipelineRun {
	p.pipelineRunDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pipelineRun) As(alias string) *pipelineRun {
	p.pipelineRunDo.DO = *(p.pipelineRunDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pipelineRun) updateTableName(table string) *pipelineRun {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint64(table, "id")
	p.PipelineID = field.NewUint32(table, "pipeline_id")
	p.WorkflowName = field.NewString(table, "workflow_name")
	p.Status = field.NewString(table, "status")
	p.Operator = field.NewString(table, "operator")
	p.Branch = field.NewString(table, "branch")
	p.CommitID = field.NewString(table, "commit_id")
	p.StartTime = field.NewTime(table, "start_time")
	p.EndTime = field.NewTime(table, "end_time")
	p.Duration = field.NewUint32(table, "duration")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")

	p.fillFieldMap()

	return p
}

func (p *pipelineRun) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pipelineRun) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 13)
	p.fieldMap["id"] = p.ID
	p.fieldMap["pipeline_id"] = p.PipelineID
	p.fieldMap["workflow_name"] = p.WorkflowName
	p.fieldMap["status"] = p.Status
	p.fieldMap["operator"] = p.Operator
	p.fieldMap["branch"] = p.Branch
	p.fieldMap["commit_id"] = p.CommitID
	p.fieldMap["start_time"] = p.StartTime
	p.fieldMap["end_time"] = p.EndTime
	p.fieldMap["duration"] = p.Duration
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
}

func (p pipelineRun) clone(db *gorm.DB) pipelineRun {
	p.pipelineRunDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pipelineRun) replaceDB(db *gorm.DB) pipelineRun {
	p.pipelineRunDo.ReplaceDB(db)
	return p
}

type pipelineRunDo struct{ gen.DO }

type IPipelineRunDo interface {
	gen.SubQuery
	Debug() IPipelineRunDo
	WithContext(ctx context.Context) IPipelineRunDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPipelineRunDo
	WriteDB() IPipelineRunDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPipelineRunDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPipelineRunDo
	Not(conds ...gen.Condition) IPipelineRunDo
	Or(conds ...gen.Condition) IPipelineRunDo
	Select(conds ...field.Expr) IPipelineRunDo
	Where(conds ...gen.Condition) IPipelineRunDo
	Order(conds ...field.Expr) IPipelineRunDo
	Distinct(cols ...field.Expr) IPipelineRunDo
	Omit(cols ...field.Expr) IPipelineRunDo
	Join(table schema.Tabler, on ...field.Expr) IPipelineRunDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPipelineRunDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPipelineRunDo
	Group(cols ...field.Expr) IPipelineRunDo
	Having(conds ...gen.Condition) IPipelineRunDo
	Limit(limit int) IPipelineRunDo
	Offset(offset int) IPipelineRunDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPipelineRunDo
	Unscoped() IPipelineRunDo
	Create(values ...*model.PipelineRun) error
	CreateInBatches(values []*model.PipelineRun, batchSize int) error
	Save(values ...*model.PipelineRun) error
	First() (*model.PipelineRun, error)
	Take() (*model.PipelineRun, error)
	Last() (*model.PipelineRun, error)
	Find() ([]*model.PipelineRun, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PipelineRun, err error)
	FindInBatches(result *[]*model.PipelineRun, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PipelineRun) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPipelineRunDo
	Assign(attrs ...field.AssignExpr) IPipelineRunDo
	Joins(fields ...field.RelationField) IPipelineRunDo
	Preload(fields ...field.RelationField) IPipelineRunDo
	FirstOrInit() (*model.PipelineRun, error)
	FirstOrCreate() (*model.PipelineRun, error)
	FindByPage(offset int, limit int) (result []*model.PipelineRun, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPipelineRunDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p pipelineRunDo) Debug() IPipelineRunDo {
	return p.withDO(p.DO.Debug())
}

func (p pipelineRunDo) WithContext(ctx context.Context) IPipelineRunDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pipelineRunDo) ReadDB() IPipelineRunDo {
	return p.Clauses(dbresolver.Read)
}

func (p pipelineRunDo) WriteDB() IPipelineRunDo {
	return p.Clauses(dbresolver.Write)
}

func (p pipelineRunDo) Session(config *gorm.Session) IPipelineRunDo {
	return p.withDO(p.DO.Session(config))
}

func (p pipelineRunDo) Clauses(conds ...clause.Expression) IPipelineRunDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pipelineRunDo) Returning(value interface{}, columns ...string) IPipelineRunDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pipelineRunDo) Not(conds ...gen.Condition) IPipelineRunDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pipelineRunDo) Or(conds ...gen.Condition) IPipelineRunDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pipelineRunDo) Select(conds ...field.Expr) IPipelineRunDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pipelineRunDo) Where(conds ...gen.Condition) IPipelineRunDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pipelineRunDo) Order(conds ...field.Expr) IPipelineRunDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pipelineRunDo) Distinct(cols ...field.Expr) IPipelineRunDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pipelineRunDo) Omit(cols ...field.Expr) IPipelineRunDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pipelineRunDo) Join(table schema.Tabler, on ...field.Expr) IPipelineRunDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pipelineRunDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPipelineRunDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pipelineRunDo) RightJoin(table schema.Tabler, on ...field.Expr) IPipelineRunDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pipelineRunDo) Group(cols ...field.Expr) IPipelineRunDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pipelineRunDo) Having(conds ...gen.Condition) IPipelineRunDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pipelineRunDo) Limit(limit int) IPipelineRunDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pipelineRunDo) Offset(offset int) IPipelineRunDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pipelineRunDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPipelineRunDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pipelineRunDo) Unscoped() IPipelineRunDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pipelineRunDo) Create(values ...*model.PipelineRun) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pipelineRunDo) CreateInBatches(values []*model.PipelineRun, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pipelineRunDo) Save(values ...*model.PipelineRun) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pipelineRunDo) First() (*model.PipelineRun, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PipelineRun), nil
	}
}

func (p pipelineRunDo) Take() (*model.PipelineRun, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PipelineRun), nil
	}
}

func (p pipelineRunDo) Last() (*model.PipelineRun, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PipelineRun), nil
	}
}

func (p pipelineRunDo) Find() ([]*model.PipelineRun, error) {
	result, err := p.DO.Find()
	return result.([]*model.PipelineRun), err
}

func (p pipelineRunDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PipelineRun, err error) {
	buf := make([]*model.PipelineRun, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pipelineRunDo) FindInBatches(result *[]*model.PipelineRun, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pipelineRunDo) Attrs(attrs ...field.AssignExpr) IPipelineRunDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pipelineRunDo) Assign(attrs ...field.AssignExpr) IPipelineRunDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pipelineRunDo) Joins(fields ...field.RelationField) IPipelineRunDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pipelineRunDo) Preload(fields ...field.RelationField) IPipelineRunDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pipelineRunDo) FirstOrInit() (*model.PipelineRun, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PipelineRun), nil
	}
}

func (p pipelineRunDo) FirstOrCreate() (*model.PipelineRun, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PipelineRun), nil
	}
}

func (p pipelineRunDo) FindByPage(offset int, limit int) (result []*model.PipelineRun, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pipelineRunDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pipelineRunDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pipelineRunDo) Delete(models ...*model.PipelineRun) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pipelineRunDo) withDO(do gen.Dao) *pipelineRunDo {
	p.DO = *do.(*gen.DO)
	return p
}
