// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"devops-console-backend/internal/dal/model"
)

func newResourceDetail(db *gorm.DB, opts ...gen.DOOption) resourceDetail {
	_resourceDetail := resourceDetail{}

	_resourceDetail.resourceDetailDo.UseDB(db, opts...)
	_resourceDetail.resourceDetailDo.UseModel(&model.ResourceDetail{})

	tableName := _resourceDetail.resourceDetailDo.TableName()
	_resourceDetail.ALL = field.NewAsterisk(tableName)
	_resourceDetail.ResourceType = field.NewString(tableName, "resource_type")
	_resourceDetail.ResourceID = field.NewUint64(tableName, "resource_id")
	_resourceDetail.ResourceName = field.NewString(tableName, "resource_name")
	_resourceDetail.Status = field.NewString(tableName, "status")
	_resourceDetail.CreatedAt = field.NewTime(tableName, "created_at")
	_resourceDetail.UpdatedAt = field.NewTime(tableName, "updated_at")
	_resourceDetail.AuthConfigs = field.NewString(tableName, "auth_configs")
	_resourceDetail.AuthTypeDesc = field.NewString(tableName, "auth_type_desc")
	_resourceDetail.ConnectionEndpoint = field.NewString(tableName, "connection_endpoint")
	_resourceDetail.SecureConnection = field.NewBool(tableName, "secure_connection")
	_resourceDetail.SslVerificationDisabled = field.NewBool(tableName, "ssl_verification_disabled")
	_resourceDetail.ResourceSubtype = field.NewString(tableName, "resource_subtype")
	_resourceDetail.SubtypeDescription = field.NewString(tableName, "subtype_description")
	_resourceDetail.LastTestResult = field.NewString(tableName, "last_test_result")
	_resourceDetail.LastResponseTime = field.NewInt64(tableName, "last_response_time")
	_resourceDetail.LastTestTime = field.NewTime(tableName, "last_test_time")

	_resourceDetail.fillFieldMap()

	return _resourceDetail
}

// resourceDetail VIEW
type resourceDetail struct {
	resourceDetailDo

	ALL                     field.Asterisk
	ResourceType            field.String
	ResourceID              field.Uint64
	ResourceName            field.String
	Status                  field.String
	CreatedAt               field.Time
	UpdatedAt               field.Time
	AuthConfigs             field.String
	AuthTypeDesc            field.String
	ConnectionEndpoint      field.String
	SecureConnection        field.Bool
	SslVerificationDisabled field.Bool
	ResourceSubtype         field.String
	SubtypeDescription      field.String
	LastTestResult          field.String
	LastResponseTime        field.Int64
	LastTestTime            field.Time

	fieldMap map[string]field.Expr
}

func (r resourceDetail) Table(newTableName string) *resourceDetail {
	r.resourceDetailDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resourceDetail) As(alias string) *resourceDetail {
	r.resourceDetailDo.DO = *(r.resourceDetailDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resourceDetail) updateTableName(table string) *resourceDetail {
	r.ALL = field.NewAsterisk(table)
	r.ResourceType = field.NewString(table, "resource_type")
	r.ResourceID = field.NewUint64(table, "resource_id")
	r.ResourceName = field.NewString(table, "resource_name")
	r.Status = field.NewString(table, "status")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.AuthConfigs = field.NewString(table, "auth_configs")
	r.AuthTypeDesc = field.NewString(table, "auth_type_desc")
	r.ConnectionEndpoint = field.NewString(table, "connection_endpoint")
	r.SecureConnection = field.NewBool(table, "secure_connection")
	r.SslVerificationDisabled = field.NewBool(table, "ssl_verification_disabled")
	r.ResourceSubtype = field.NewString(table, "resource_subtype")
	r.SubtypeDescription = field.NewString(table, "subtype_description")
	r.LastTestResult = field.NewString(table, "last_test_result")
	r.LastResponseTime = field.NewInt64(table, "last_response_time")
	r.LastTestTime = field.NewTime(table, "last_test_time")

	r.fillFieldMap()

	return r
}

func (r *resourceDetail) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resourceDetail) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 16)
	r.fieldMap["resource_type"] = r.ResourceType
	r.fieldMap["resource_id"] = r.ResourceID
	r.fieldMap["resource_name"] = r.ResourceName
	r.fieldMap["status"] = r.Status
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["auth_configs"] = r.AuthConfigs
	r.fieldMap["auth_type_desc"] = r.AuthTypeDesc
	r.fieldMap["connection_endpoint"] = r.ConnectionEndpoint
	r.fieldMap["secure_connection"] = r.SecureConnection
	r.fieldMap["ssl_verification_disabled"] = r.SslVerificationDisabled
	r.fieldMap["resource_subtype"] = r.ResourceSubtype
	r.fieldMap["subtype_description"] = r.SubtypeDescription
	r.fieldMap["last_test_result"] = r.LastTestResult
	r.fieldMap["last_response_time"] = r.LastResponseTime
	r.fieldMap["last_test_time"] = r.LastTestTime
}

func (r resourceDetail) clone(db *gorm.DB) resourceDetail {
	r.resourceDetailDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resourceDetail) replaceDB(db *gorm.DB) resourceDetail {
	r.resourceDetailDo.ReplaceDB(db)
	return r
}

type resourceDetailDo struct{ gen.DO }

type IResourceDetailDo interface {
	gen.SubQuery
	Debug() IResourceDetailDo
	WithContext(ctx context.Context) IResourceDetailDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResourceDetailDo
	WriteDB() IResourceDetailDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResourceDetailDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResourceDetailDo
	Not(conds ...gen.Condition) IResourceDetailDo
	Or(conds ...gen.Condition) IResourceDetailDo
	Select(conds ...field.Expr) IResourceDetailDo
	Where(conds ...gen.Condition) IResourceDetailDo
	Order(conds ...field.Expr) IResourceDetailDo
	Distinct(cols ...field.Expr) IResourceDetailDo
	Omit(cols ...field.Expr) IResourceDetailDo
	Join(table schema.Tabler, on ...field.Expr) IResourceDetailDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResourceDetailDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResourceDetailDo
	Group(cols ...field.Expr) IResourceDetailDo
	Having(conds ...gen.Condition) IResourceDetailDo
	Limit(limit int) IResourceDetailDo
	Offset(offset int) IResourceDetailDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceDetailDo
	Unscoped() IResourceDetailDo
	Create(values ...*model.ResourceDetail) error
	CreateInBatches(values []*model.ResourceDetail, batchSize int) error
	Save(values ...*model.ResourceDetail) error
	First() (*model.ResourceDetail, error)
	Take() (*model.ResourceDetail, error)
	Last() (*model.ResourceDetail, error)
	Find() ([]*model.ResourceDetail, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceDetail, err error)
	FindInBatches(result *[]*model.ResourceDetail, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ResourceDetail) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResourceDetailDo
	Assign(attrs ...field.AssignExpr) IResourceDetailDo
	Joins(fields ...field.RelationField) IResourceDetailDo
	Preload(fields ...field.RelationField) IResourceDetailDo
	FirstOrInit() (*model.ResourceDetail, error)
	FirstOrCreate() (*model.ResourceDetail, error)
	FindByPage(offset int, limit int) (result []*model.ResourceDetail, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResourceDetailDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resourceDetailDo) Debug() IResourceDetailDo {
	return r.withDO(r.DO.Debug())
}

func (r resourceDetailDo) WithContext(ctx context.Context) IResourceDetailDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resourceDetailDo) ReadDB() IResourceDetailDo {
	return r.Clauses(dbresolver.Read)
}

func (r resourceDetailDo) WriteDB() IResourceDetailDo {
	return r.Clauses(dbresolver.Write)
}

func (r resourceDetailDo) Session(config *gorm.Session) IResourceDetailDo {
	return r.withDO(r.DO.Session(config))
}

func (r resourceDetailDo) Clauses(conds ...clause.Expression) IResourceDetailDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resourceDetailDo) Returning(value interface{}, columns ...string) IResourceDetailDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resourceDetailDo) Not(conds ...gen.Condition) IResourceDetailDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resourceDetailDo) Or(conds ...gen.Condition) IResourceDetailDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resourceDetailDo) Select(conds ...field.Expr) IResourceDetailDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resourceDetailDo) Where(conds ...gen.Condition) IResourceDetailDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resourceDetailDo) Order(conds ...field.Expr) IResourceDetailDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resourceDetailDo) Distinct(cols ...field.Expr) IResourceDetailDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resourceDetailDo) Omit(cols ...field.Expr) IResourceDetailDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resourceDetailDo) Join(table schema.Tabler, on ...field.Expr) IResourceDetailDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resourceDetailDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResourceDetailDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resourceDetailDo) RightJoin(table schema.Tabler, on ...field.Expr) IResourceDetailDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resourceDetailDo) Group(cols ...field.Expr) IResourceDetailDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resourceDetailDo) Having(conds ...gen.Condition) IResourceDetailDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resourceDetailDo) Limit(limit int) IResourceDetailDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resourceDetailDo) Offset(offset int) IResourceDetailDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resourceDetailDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceDetailDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resourceDetailDo) Unscoped() IResourceDetailDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resourceDetailDo) Create(values ...*model.ResourceDetail) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resourceDetailDo) CreateInBatches(values []*model.ResourceDetail, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resourceDetailDo) Save(values ...*model.ResourceDetail) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resourceDetailDo) First() (*model.ResourceDetail, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceDetail), nil
	}
}

func (r resourceDetailDo) Take() (*model.ResourceDetail, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceDetail), nil
	}
}

func (r resourceDetailDo) Last() (*model.ResourceDetail, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceDetail), nil
	}
}

func (r resourceDetailDo) Find() ([]*model.ResourceDetail, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResourceDetail), err
}

func (r resourceDetailDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceDetail, err error) {
	buf := make([]*model.ResourceDetail, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resourceDetailDo) FindInBatches(result *[]*model.ResourceDetail, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resourceDetailDo) Attrs(attrs ...field.AssignExpr) IResourceDetailDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resourceDetailDo) Assign(attrs ...field.AssignExpr) IResourceDetailDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resourceDetailDo) Joins(fields ...field.RelationField) IResourceDetailDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resourceDetailDo) Preload(fields ...field.RelationField) IResourceDetailDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resourceDetailDo) FirstOrInit() (*model.ResourceDetail, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceDetail), nil
	}
}

func (r resourceDetailDo) FirstOrCreate() (*model.ResourceDetail, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceDetail), nil
	}
}

func (r resourceDetailDo) FindByPage(offset int, limit int) (result []*model.ResourceDetail, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resourceDetailDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resourceDetailDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resourceDetailDo) Delete(models ...*model.ResourceDetail) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resourceDetailDo) withDO(do gen.Dao) *resourceDetailDo {
	r.DO = *do.(*gen.DO)
	return r
}
