// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"devops-console-backend/internal/dal/model"
)

func newSystemUserToken(db *gorm.DB, opts ...gen.DOOption) systemUserToken {
	_systemUserToken := systemUserToken{}

	_systemUserToken.systemUserTokenDo.UseDB(db, opts...)
	_systemUserToken.systemUserTokenDo.UseModel(&model.SystemUserToken{})

	tableName := _systemUserToken.systemUserTokenDo.TableName()
	_systemUserToken.ALL = field.NewAsterisk(tableName)
	_systemUserToken.ID = field.NewUint64(tableName, "id")
	_systemUserToken.UserID = field.NewInt64(tableName, "user_id")
	_systemUserToken.RefreshToken = field.NewString(tableName, "refresh_token")
	_systemUserToken.ExpiresAt = field.NewTime(tableName, "expires_at")
	_systemUserToken.LastLoginIP = field.NewString(tableName, "last_login_ip")
	_systemUserToken.CreatedAt = field.NewTime(tableName, "created_at")
	_systemUserToken.UpdateAt = field.NewTime(tableName, "update_at")
	_systemUserToken.DeletedAt = field.NewField(tableName, "deleted_at")
	_systemUserToken.AccessToken = field.NewString(tableName, "access_token")

	_systemUserToken.fillFieldMap()

	return _systemUserToken
}

type systemUserToken struct {
	systemUserTokenDo

	ALL          field.Asterisk
	ID           field.Uint64 // 主键id
	UserID       field.Int64  // 用户id
	RefreshToken field.String // 刷新token
	ExpiresAt    field.Time   // 超时时间
	LastLoginIP  field.String // 最后登录的ip地址
	CreatedAt    field.Time   // 创建时间
	UpdateAt     field.Time   // 更新时间
	DeletedAt    field.Field  // 删除时间
	AccessToken  field.String // 登录token

	fieldMap map[string]field.Expr
}

func (s systemUserToken) Table(newTableName string) *systemUserToken {
	s.systemUserTokenDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemUserToken) As(alias string) *systemUserToken {
	s.systemUserTokenDo.DO = *(s.systemUserTokenDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemUserToken) updateTableName(table string) *systemUserToken {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.UserID = field.NewInt64(table, "user_id")
	s.RefreshToken = field.NewString(table, "refresh_token")
	s.ExpiresAt = field.NewTime(table, "expires_at")
	s.LastLoginIP = field.NewString(table, "last_login_ip")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdateAt = field.NewTime(table, "update_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.AccessToken = field.NewString(table, "access_token")

	s.fillFieldMap()

	return s
}

func (s *systemUserToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemUserToken) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["refresh_token"] = s.RefreshToken
	s.fieldMap["expires_at"] = s.ExpiresAt
	s.fieldMap["last_login_ip"] = s.LastLoginIP
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["update_at"] = s.UpdateAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["access_token"] = s.AccessToken
}

func (s systemUserToken) clone(db *gorm.DB) systemUserToken {
	s.systemUserTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemUserToken) replaceDB(db *gorm.DB) systemUserToken {
	s.systemUserTokenDo.ReplaceDB(db)
	return s
}

type systemUserTokenDo struct{ gen.DO }

type ISystemUserTokenDo interface {
	gen.SubQuery
	Debug() ISystemUserTokenDo
	WithContext(ctx context.Context) ISystemUserTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemUserTokenDo
	WriteDB() ISystemUserTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemUserTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemUserTokenDo
	Not(conds ...gen.Condition) ISystemUserTokenDo
	Or(conds ...gen.Condition) ISystemUserTokenDo
	Select(conds ...field.Expr) ISystemUserTokenDo
	Where(conds ...gen.Condition) ISystemUserTokenDo
	Order(conds ...field.Expr) ISystemUserTokenDo
	Distinct(cols ...field.Expr) ISystemUserTokenDo
	Omit(cols ...field.Expr) ISystemUserTokenDo
	Join(table schema.Tabler, on ...field.Expr) ISystemUserTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemUserTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemUserTokenDo
	Group(cols ...field.Expr) ISystemUserTokenDo
	Having(conds ...gen.Condition) ISystemUserTokenDo
	Limit(limit int) ISystemUserTokenDo
	Offset(offset int) ISystemUserTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemUserTokenDo
	Unscoped() ISystemUserTokenDo
	Create(values ...*model.SystemUserToken) error
	CreateInBatches(values []*model.SystemUserToken, batchSize int) error
	Save(values ...*model.SystemUserToken) error
	First() (*model.SystemUserToken, error)
	Take() (*model.SystemUserToken, error)
	Last() (*model.SystemUserToken, error)
	Find() ([]*model.SystemUserToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemUserToken, err error)
	FindInBatches(result *[]*model.SystemUserToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemUserToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemUserTokenDo
	Assign(attrs ...field.AssignExpr) ISystemUserTokenDo
	Joins(fields ...field.RelationField) ISystemUserTokenDo
	Preload(fields ...field.RelationField) ISystemUserTokenDo
	FirstOrInit() (*model.SystemUserToken, error)
	FirstOrCreate() (*model.SystemUserToken, error)
	FindByPage(offset int, limit int) (result []*model.SystemUserToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemUserTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemUserTokenDo) Debug() ISystemUserTokenDo {
	return s.withDO(s.DO.Debug())
}

func (s systemUserTokenDo) WithContext(ctx context.Context) ISystemUserTokenDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemUserTokenDo) ReadDB() ISystemUserTokenDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemUserTokenDo) WriteDB() ISystemUserTokenDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemUserTokenDo) Session(config *gorm.Session) ISystemUserTokenDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemUserTokenDo) Clauses(conds ...clause.Expression) ISystemUserTokenDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemUserTokenDo) Returning(value interface{}, columns ...string) ISystemUserTokenDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemUserTokenDo) Not(conds ...gen.Condition) ISystemUserTokenDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemUserTokenDo) Or(conds ...gen.Condition) ISystemUserTokenDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemUserTokenDo) Select(conds ...field.Expr) ISystemUserTokenDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemUserTokenDo) Where(conds ...gen.Condition) ISystemUserTokenDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemUserTokenDo) Order(conds ...field.Expr) ISystemUserTokenDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemUserTokenDo) Distinct(cols ...field.Expr) ISystemUserTokenDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemUserTokenDo) Omit(cols ...field.Expr) ISystemUserTokenDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemUserTokenDo) Join(table schema.Tabler, on ...field.Expr) ISystemUserTokenDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemUserTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemUserTokenDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemUserTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemUserTokenDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemUserTokenDo) Group(cols ...field.Expr) ISystemUserTokenDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemUserTokenDo) Having(conds ...gen.Condition) ISystemUserTokenDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemUserTokenDo) Limit(limit int) ISystemUserTokenDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemUserTokenDo) Offset(offset int) ISystemUserTokenDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemUserTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemUserTokenDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemUserTokenDo) Unscoped() ISystemUserTokenDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemUserTokenDo) Create(values ...*model.SystemUserToken) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemUserTokenDo) CreateInBatches(values []*model.SystemUserToken, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemUserTokenDo) Save(values ...*model.SystemUserToken) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemUserTokenDo) First() (*model.SystemUserToken, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemUserToken), nil
	}
}

func (s systemUserTokenDo) Take() (*model.SystemUserToken, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemUserToken), nil
	}
}

func (s systemUserTokenDo) Last() (*model.SystemUserToken, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemUserToken), nil
	}
}

func (s systemUserTokenDo) Find() ([]*model.SystemUserToken, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemUserToken), err
}

func (s systemUserTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemUserToken, err error) {
	buf := make([]*model.SystemUserToken, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemUserTokenDo) FindInBatches(result *[]*model.SystemUserToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemUserTokenDo) Attrs(attrs ...field.AssignExpr) ISystemUserTokenDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemUserTokenDo) Assign(attrs ...field.AssignExpr) ISystemUserTokenDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemUserTokenDo) Joins(fields ...field.RelationField) ISystemUserTokenDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemUserTokenDo) Preload(fields ...field.RelationField) ISystemUserTokenDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemUserTokenDo) FirstOrInit() (*model.SystemUserToken, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemUserToken), nil
	}
}

func (s systemUserTokenDo) FirstOrCreate() (*model.SystemUserToken, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemUserToken), nil
	}
}

func (s systemUserTokenDo) FindByPage(offset int, limit int) (result []*model.SystemUserToken, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemUserTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemUserTokenDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemUserTokenDo) Delete(models ...*model.SystemUserToken) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemUserTokenDo) withDO(do gen.Dao) *systemUserTokenDo {
	s.DO = *do.(*gen.DO)
	return s
}
