// Status generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireInfo

import (
	"devops-console-backend/internal/controllers/system"
	"devops-console-backend/internal/dal/mapper"
	"devops-console-backend/internal/dal/redis"
	"devops-console-backend/pkg/configs"
	"devops-console-backend/pkg/database"
)

// Injectors from wire.go:

func InitializeLoginController() *system.LoginController {
	db := configs.NewDB()
	userMapper := mapper.NewUserMapper(db)
	client := database.InitRedis()
	redisClient := redis.NewClient(client)
	loginController := system.NewLoginController(userMapper, redisClient)
	return loginController
}
