// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuthConfig = "auth_configs"

// AuthConfig mapped from table <auth_configs>
type AuthConfig struct {
	ID           uint32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	ResourceType string     `gorm:"column:resource_type;type:varchar(191);not null;uniqueIndex:unique_resource_config,priority:1;index:idx_auth_configs_resource,priority:1;index:idx_auth_configs_resource_type,priority:1" json:"resourceType"`
	ResourceID   uint64     `gorm:"column:resource_id;type:bigint unsigned;not null;uniqueIndex:unique_resource_config,priority:2;index:idx_auth_configs_resource,priority:2;index:idx_auth_configs_resource_id,priority:1" json:"resourceId"`
	ResourceName string     `gorm:"column:resource_name;type:varchar(255);not null" json:"resourceName"`
	AuthType     string     `gorm:"column:auth_type;type:varchar(191);not null;index:idx_auth_configs_auth_type,priority:1;index:idx_auth_configs_type,priority:1" json:"authType"`
	ConfigKey    string     `gorm:"column:config_key;type:varchar(100);not null;uniqueIndex:unique_resource_config,priority:3" json:"configKey"`
	ConfigValue  *string    `gorm:"column:config_value;type:longtext" json:"configValue"`
	IsEncrypted  *bool      `gorm:"column:is_encrypted;type:tinyint(1);default:1" json:"isEncrypted"`
	Status       *string    `gorm:"column:status;type:varchar(191);index:idx_auth_configs_status,priority:1;default:active" json:"status"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:datetime(3)" json:"createdAt"`
	UpdatedAt    *time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updatedAt"`
}

// TableName AuthConfig's table name
func (*AuthConfig) TableName() string {
	return TableNameAuthConfig
}
