// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConnectionTest = "connection_tests"

// ConnectionTest mapped from table <connection_tests>
type ConnectionTest struct {
	ID           uint32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	ResourceType string     `gorm:"column:resource_type;type:varchar(191);not null;index:idx_connection_tests_resource,priority:1;index:idx_connection_tests_resource_type,priority:1" json:"resourceType"`
	ResourceID   uint64     `gorm:"column:resource_id;type:bigint unsigned;not null;index:idx_connection_tests_resource,priority:2;index:idx_connection_tests_resource_id,priority:1" json:"resourceId"`
	TestResult   *string    `gorm:"column:test_result;type:longtext" json:"testResult"`
	ResponseTime *int64     `gorm:"column:response_time;type:bigint" json:"responseTime"`
	ErrorMessage *string    `gorm:"column:error_message;type:longtext" json:"errorMessage"`
	TestedAt     *time.Time `gorm:"column:tested_at;type:datetime(3);index:idx_connection_tests_tested_at,priority:1;index:idx_connection_tests_time,priority:1" json:"testedAt"`
}

// TableName ConnectionTest's table name
func (*ConnectionTest) TableName() string {
	return TableNameConnectionTest
}
