// Status generated by gorm.io/gen. DO NOT EDIT.
// Status generated by gorm.io/gen. DO NOT EDIT.
// Status generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInstanceType = "instance_types"

// InstanceType mapped from table <instance_types>
type InstanceType struct {
	ID          uint32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	TypeName    string     `gorm:"column:type_name;type:varchar(100);not null;uniqueIndex:uni_instance_types_type_name,priority:1" json:"typeName"`
	Description *string    `gorm:"column:description;type:longtext" json:"description"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime(3)" json:"createdAt"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updatedAt"`
}

// TableName InstanceType's table name
func (*InstanceType) TableName() string {
	return TableNameInstanceType
}
