// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInstance = "instances"

// Instance mapped from table <instances>
type Instance struct {
	ID             uint32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	InstanceTypeID uint32     `gorm:"column:instance_type_id;type:int unsigned;not null;index:idx_instances_instance_type_id,priority:1;index:idx_instances_type,priority:1" json:"instanceTypeId"`
	Name           string     `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Address        string     `gorm:"column:address;type:varchar(500);not null" json:"address"`
	HTTPSEnabled   *bool      `gorm:"column:https_enabled;type:tinyint(1);index:idx_instances_https,priority:1;index:idx_instances_https_enabled,priority:1" json:"httpsEnabled"`
	SkipSslVerify  *bool      `gorm:"column:skip_ssl_verify;type:tinyint(1)" json:"skipSslVerify"`
	Status         *string    `gorm:"column:status;type:varchar(191);index:idx_instances_status,priority:1;default:active" json:"status"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:datetime(3)" json:"createdAt"`
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updatedAt"`
}

// TableName Instance's table name
func (*Instance) TableName() string {
	return TableNameInstance
}
