// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePipelineRun = "pipeline_runs"

// PipelineRun 流水线执行记录表
type PipelineRun struct {
	ID           uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	PipelineID   uint32         `gorm:"column:pipeline_id;type:int unsigned;not null;index:idx_pipeline_id,priority:1;comment:关联流水线ID" json:"pipelineId"`                      // 关联流水线ID
	WorkflowName string         `gorm:"column:workflow_name;type:varchar(128);not null;uniqueIndex:uk_workflow_name,priority:1;comment:K8s中生成的Workflow名称" json:"workflowName"` // K8s中生成的Workflow名称
	Status       *string        `gorm:"column:status;type:enum('Pending','Running','Succeeded','Failed','Error','Omitted');default:Pending;comment:运行状态" json:"status"`        // 运行状态
	Operator     string         `gorm:"column:operator;type:varchar(64);not null;comment:执行人" json:"operator"`                                                                 // 执行人
	Branch       *string        `gorm:"column:branch;type:varchar(64);comment:本次构建实际使用的分支" json:"branch"`                                                                      // 本次构建实际使用的分支
	CommitID     *string        `gorm:"column:commit_id;type:varchar(64);comment:代码CommitID" json:"commitId"`                                                                  // 代码CommitID
	StartTime    *time.Time     `gorm:"column:start_time;type:timestamp;comment:开始时间" json:"startTime"`                                                                        // 开始时间
	EndTime      *time.Time     `gorm:"column:end_time;type:timestamp;comment:结束时间" json:"endTime"`                                                                            // 结束时间
	Duration     *uint32        `gorm:"column:duration;type:int unsigned;comment:执行耗时，单位秒" json:"duration"`                                                                    // 执行耗时，单位秒
	CreatedAt    *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updatedAt"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deletedAt"`
}

// TableName PipelineRun's table name
func (*PipelineRun) TableName() string {
	return TableNamePipelineRun
}
