// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePipelineStep = "pipeline_steps"

// PipelineStep 流水线步骤详情表
type PipelineStep struct {
	ID         uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	PipelineID uint32         `gorm:"column:pipeline_id;type:int unsigned;not null;index:idx_pipeline_id,priority:1;comment:所属流水线ID" json:"pipelineId"` // 所属流水线ID
	Name       string         `gorm:"column:name;type:varchar(64);not null;comment:步骤名称" json:"name"`                                                   // 步骤名称
	Image      string         `gorm:"column:image;type:varchar(255);not null;comment:使用的镜像" json:"image"`                                               // 使用的镜像
	Commands   string         `gorm:"column:commands;type:text;not null;comment:运行命令" json:"commands"`                                                  // 运行命令
	DependsOn  *string        `gorm:"column:depends_on;type:varchar(64);comment:依赖的步骤名称" json:"dependsOn"`                                              // 依赖的步骤名称
	Sort       *int32         `gorm:"column:sort;type:int;comment:排序" json:"sort"`                                                                      // 排序
	CreatedAt  *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"createdAt"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deletedAt"` // 删除时间
}

// TableName PipelineStep's table name
func (*PipelineStep) TableName() string {
	return TableNamePipelineStep
}
