// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePipeline = "pipelines"

// Pipeline 流水线定义表
type Pipeline struct {
	ID            uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	ProjectID     uint32         `gorm:"column:project_id;type:int unsigned;not null;index:idx_project_id,priority:1;comment:关联项目ID" json:"projectId"` // 关联项目ID
	K8sInstanceID uint32         `gorm:"column:k8s_instance_id;type:int unsigned;not null;comment:目标K8s集群实例ID" json:"k8sInstanceId"`                   // 目标K8s集群实例ID
	Name          string         `gorm:"column:name;type:varchar(64);not null;comment:流水线名称" json:"name"`                                              // 流水线名称
	GitURL        string         `gorm:"column:git_url;type:varchar(255);not null;comment:代码仓库地址" json:"gitUrl"`                                       // 代码仓库地址
	Branch        *string        `gorm:"column:branch;type:varchar(64);default:main;comment:默认构建分支" json:"branch"`                                     // 默认构建分支
	ArgoTemplate  string         `gorm:"column:argo_template;type:varchar(64);not null;comment:关联的 Argo WorkflowTemplate 名称" json:"argoTemplate"`      // 关联的 Argo WorkflowTemplate 名称
	ParamsConfig  *string        `gorm:"column:params_config;type:json;comment:自定义参数配置(环境变量、构建参数等)" json:"paramsConfig"`                               // 自定义参数配置(环境变量、构建参数等)
	CreatedAt     *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt     *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updatedAt"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deletedAt"`
}

// TableName Pipeline's table name
func (*Pipeline) TableName() string {
	return TableNamePipeline
}
