// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "projects"

// Project 项目表
type Project struct {
	ID          uint32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name        string     `gorm:"column:name;type:varchar(64);not null;uniqueIndex:uk_name,priority:1;comment:项目名称" json:"name"` // 项目名称
	Description *string    `gorm:"column:description;type:varchar(255);comment:项目描述" json:"description"`                          // 项目描述
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
