// Status generated by gorm.io/gen. DO NOT EDIT.
// Status generated by gorm.io/gen. DO NOT EDIT.
// Status generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResourceDetail = "resource_details"

// ResourceDetail VIEW
type ResourceDetail struct {
	ResourceType            string     `gorm:"column:resource_type;type:varchar(191);not null" json:"resourceType"`
	ResourceID              uint64     `gorm:"column:resource_id;type:bigint unsigned;not null" json:"resourceId"`
	ResourceName            string     `gorm:"column:resource_name;type:varchar(255);not null" json:"resourceName"`
	Status                  *string    `gorm:"column:status;type:varchar(191);default:active" json:"status"`
	CreatedAt               *time.Time `gorm:"column:created_at;type:datetime(3)" json:"createdAt"`
	UpdatedAt               *time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updatedAt"`
	AuthConfigs             *string    `gorm:"column:auth_configs;type:json" json:"authConfigs"`
	AuthTypeDesc            string     `gorm:"column:auth_type_desc;type:varchar(9);not null" json:"authTypeDesc"`
	ConnectionEndpoint      *string    `gorm:"column:connection_endpoint;type:varchar(500)" json:"connectionEndpoint"`
	SecureConnection        *bool      `gorm:"column:secure_connection;type:tinyint(1)" json:"secureConnection"`
	SslVerificationDisabled *bool      `gorm:"column:ssl_verification_disabled;type:tinyint(1)" json:"sslVerificationDisabled"`
	ResourceSubtype         *string    `gorm:"column:resource_subtype;type:varchar(100)" json:"resourceSubtype"`
	SubtypeDescription      *string    `gorm:"column:subtype_description;type:longtext" json:"subtypeDescription"`
	LastTestResult          *string    `gorm:"column:last_test_result;type:longtext" json:"lastTestResult"`
	LastResponseTime        *int64     `gorm:"column:last_response_time;type:bigint" json:"lastResponseTime"`
	LastTestTime            *time.Time `gorm:"column:last_test_time;type:datetime(3)" json:"lastTestTime"`
}

// TableName ResourceDetail's table name
func (*ResourceDetail) TableName() string {
	return TableNameResourceDetail
}
