// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSystemUser = "system_users"

// SystemUser mapped from table <system_users>
type SystemUser struct {
	ID        uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	Username  string         `gorm:"column:username;type:varchar(191);not null;index:idx_account_user_id,priority:1" json:"username"`
	Password  string         `gorm:"column:password;type:varchar(191);not null" json:"password"`
	Status    uint32         `gorm:"column:status;type:tinyint unsigned;not null" json:"status"`
	Nickname  *string        `gorm:"column:nickname;type:varchar(191)" json:"nickname"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"createdAt"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updatedAt"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_account_deleted_at,priority:1" json:"deletedAt"`
}

// TableName SystemUser's table name
func (*SystemUser) TableName() string {
	return TableNameSystemUser
}
