// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSystemUserToken = "system_user_token"

// SystemUserToken mapped from table <system_user_token>
type SystemUserToken struct {
	ID           int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                      // 主键id
	UserID       int64          `gorm:"column:user_id;type:bigint;not null;uniqueIndex:uniq_user,priority:1;comment:用户id" json:"userId"` // 用户id
	RefreshToken string         `gorm:"column:refresh_token;type:varchar(255);not null;comment:刷新token" json:"refreshToken"`             // 刷新token
	ExpiresAt    time.Time      `gorm:"column:expires_at;type:datetime;not null;comment:超时时间" json:"expiresAt"`                          // 超时时间
	LastLoginIP  *string        `gorm:"column:last_login_ip;type:varchar(45);comment:最后登录的ip地址" json:"lastLoginIp"`                      // 最后登录的ip地址
	CreatedAt    *time.Time     `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createdAt"`         // 创建时间
	UpdateAt     *time.Time     `gorm:"column:update_at;type:datetime;comment:更新时间" json:"updateAt"`                                     // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deletedAt"`                                   // 删除时间
	AccessToken  string         `gorm:"column:access_token;type:varchar(255);not null;comment:登录token" json:"accessToken"`               // 登录token
}

// TableName SystemUserToken's table name
func (*SystemUserToken) TableName() string {
	return TableNameSystemUserToken
}
